version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend/rag_chatbot_data:/app/rag_chatbot_data
      - ./backend:/app
    networks:
      - chatbot-network
    restart: unless-stopped
    

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    networks:
      - chatbot-network
    restart: unless-stopped
    volumes:
      - ./frontend:/app

networks:
  chatbot-network:
    driver: bridge

volumes:
  rag_data:
    driver: local